obj-y += tccmisc_drv.o
obj-$(CONFIG_TCC_SHMEM) += tcc_shared_mem.o
obj-$(CONFIG_TCC_WMIXER) += wmixer_drv.o
obj-$(CONFIG_TCC_SCALER) += scaler_drv.o
obj-$(CONFIG_TCC_SDR) += tcc_sdr/tcc_sdr.o
obj-$(CONFIG_TCC_G2D) += tcc_grp.o
obj-$(CONFIG_GPIO_TCC_SAMPLE)   += gpio-tcc-sample.o
