# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) Telechips Inc.

obj-y	+= board-tcc897x.o chipinfo.o

obj-$(CONFIG_SMP) += headsmp.o platsmp.o cpu_power.o io.o
obj-$(CONFIG_HOTPLUG_CPU) += hotplug.o
