# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) Telechips Inc.

obj-y	+= irq-pic.o
obj-y	+= timer.o

obj-$(CONFIG_TCC_BOOTSTAGE)	+= bootstage.o
obj-$(CONFIG_TCC_CHIPINFO)	+= chipinfo.o

obj-$(CONFIG_PM_TCC805X)	+= pm-tcc805x.o
