/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Copyright (C) Telechips Inc.
 */

#ifndef TCC_MIPI_CKC_REG_H
#define TCC_MIPI_CKC_REG_H

/*
 * MIPI CKC REG BASE
 */
#define CLKCTRL0	(0x00U)
#define MIPI_BUS_CLK	(0x00U)
#define CLKCTRL1	(0x04U)
#define MIPI_PIXEL_CLK	(0x04U)
#define PLLPMS		(0x08U)
#define PLLCON		(0x0CU)
#define PLLMON		(0x10U)
#define CLKDIVC		(0x14U)

/*
 * CLKCTRL
 */
#define CLKCTRL_CHGRQ_SHIFT	(31U)
#define CLKCTRL_SEL_SHIFT	(0U)

#define CLKCTRL_CHGRQ_MASK	((0x1U) << CLKCTRL_CHGRQ_SHIFT)
#define CLKCTRL_SEL_MASK	((0x3U) << CLKCTRL_SEL_SHIFT)

#define CLKCTRL_SEL_XIN		(0U)
#define CLKCTRL_SEL_PLL_DIRECT	(1U)
#define CLKCTRL_SEL_PLL_DIVIDER	(2U)
#define CLKCTRL_SEL_RESERVED	(3U)

/*
 * PLLPMS
 */
#define PLLPMS_RESETB_SHIFT	(31U)
#define PLLPMS_RSEL_SHIFT	(27U)
#define PLLPMS_LOCK_EN_SHIFT	(26U)
#define PLLPMS_ICP_SHIFT	(24U)
#define PLLPMS_LOCK_SHIFT	(23U)
#define PLLPMS_BYPASS_SHIFT	(21U)
#define PLLPMS_S_SHIFT		(16U)
#define PLLPMS_M_SHIFT		(6U)
#define PLLPMS_P_SHIFT		(0U)

#define PLLPMS_RESETB_MASK	((0x1U) << PLLPMS_RESETB_SHIFT)
#define PLLPMS_RSEL_MASK	((0xFU) << PLLPMS_RSEL_SHIFT)
#define PLLPMS_LOCK_EN_MASK	((0x1U) << PLLPMS_LOCK_EN_SHIFT)
#define PLLPMS_ICP_MASK	        ((0x3U) << PLLPMS_ICP_SHIFT)
#define PLLPMS_LOCK_MASK	((0x1U) << PLLPMS_LOCK_SHIFT)
#define PLLPMS_BYPASS_MASK	((0x1U) << PLLPMS_BYPASS_SHIFT)
#define PLLPMS_S_MASK		((0x7U) << PLLPMS_S_SHIFT)
#define PLLPMS_M_MASK		((0x3FFU) << PLLPMS_M_SHIFT)
#define PLLPMS_P_MASK		((0x3FU) << PLLPMS_P_SHIFT)

/*
 * PLLCON
 */
#define PLLCON_LOCK_CON_REV_SHIFT	(12U)
#define PLLCON_LOCK_CON_DLY_SHIFT	(10U)
#define PLLCON_LOCK_CON_OUT_SHIFT	(8U)
#define PLLCON_LOCK_CON_IN_SHIFT	(6U)
#define PLLCON_EXTAFC_SHIFT		(1U)
#define PLLCON_AFC_ENB_SHIFT		(0U)

#define PLLCON_LOCK_CON_REV_MASK	((0x3U) << PLLCON_LOCK_CON_REV_SHIFT)
#define PLLCON_LOCK_CON_DLY_MASK	((0x3U) << PLLCON_LOCK_CON_DLY_SHIFT)
#define PLLCON_LOCK_CON_OUT_MASK	((0x3U) << PLLCON_LOCK_CON_OUT_SHIFT)
#define PLLCON_LOCK_CON_IN_MASK		((0x3U) << PLLCON_LOCK_CON_IN_SHIFT)
#define PLLCON_EXTAFC_MASK		((0x1FU) << PLLCON_EXTAFC_SHIFT)
#define PLLCON_AFC_ENB_MASK		((0x1U) << PLLCON_AFC_ENB_SHIFT)

/*
 * PLLMON
 */
#define PLLMON_AFCINIT_SEL_SHIFT	(15U)
#define PLLMON_FOUT_MASK_SHIFT		(14U)
#define PLLMON_FEED_EN_SHIFT		(13U)
#define PLLMON_FSEL_SHIFT		(12U)
#define PLLMON_LRD_EN_SHIFT		(11U)
#define PLLMON_VCO_BOOST_SHIFT		(10U)
#define PLLMON_PBIAS_CTRL_EN_SHIFT	(9U)
#define PLLMON_PBIAS_CTRL__SHIFT	(8U)
#define PLLMON_AFC_CODE_SHIFT		(0U)

#define PLLMON_AFCINIT_SEL_MASK		((0x1U) << PLLMON_AFCINIT_SEL_SHIFT)
#define PLLMON_FOUT_MASK_MASK		((0x1U) << PLLMON_FOUT_MASK_SHIFT)
#define PLLMON_FEED_EN_MASK		((0x1U) << PLLMON_FEED_EN_SHIFT)
#define PLLMON_FSEL_MASK		((0x1U) << PLLMON_FSEL_SHIFT)
#define PLLMON_LRD_EN_MASK		((0x1U) << PLLMON_LRD_EN_SHIFT)
#define PLLMON_VCO_BOOST_MASK		((0x1U) << PLLMON_VCO_BOOST_SHIFT)
#define PLLMON_PBIAS_CTRL_EN_MASK	((0x1U) << PLLMON_PBIAS_CTRL_EN_SHIFT)
#define PLLMON_PBIAS_CTRL__MASK		((0x1U) << PLLMON_PBIAS_CTRL__SHIFT)
#define PLLMON_AFC_CODE_MASK		(((0x1FU) << PLLMON_AFC_CODE_SHIFT))

/*
 * CLKDIVC
 */
#define CLKDIVC_PE_SHIFT		(7U)
#define CLKDIVC_PDIV_SHIFT		(0U)

#define CLKDIVC_PE_MASK			((0x1U) << CLKDIVC_PE_SHIFT)
#define CLKDIVC_PDIV_MASK		((0x3FU) << CLKDIVC_PDIV_SHIFT)

#endif
