/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Copyright (C) Telechips Inc.
 */

#ifndef TCC_MIPI_CFG_REG_H
#define TCC_MIPI_CFG_REG_H

/*
 * MIPI CFG BASE
 */
#define CSI0_CFG		(0X000U)
#define CSI1_CFG		(0X004U)
#define CSI0_DPHY_STATUS0	(0X008U)
#define CSI0_DPHY_STATUS1	(0X00CU)
#define CSI0_DPHY_STATUS2	(0X010U)
#define CSI0_DPHY_STATUS3	(0X014U)
#define CSI0_DPHY_STATUS4	(0X018U)
#define CSI1_DPHY_STATUS0	(0X01CU)
#define CSI1_DPHY_STATUS1	(0X020U)
#define CSI1_DPHY_STATUS2	(0X024U)
#define CSI1_DPHY_STATUS3	(0X028U)
#define CSI1_DPHY_STATUS4	(0X02CU)
#define ISP_CLK_MASK		(0X200U)
#define ISP_SWRST		(0X204U)
#define ISP_PX1X_DIV		(0X208U)
#define ISP_BYPASS		(0X20CU)
#define ISP_X2X_CFG		(0X210U)
#define ISP_FMT_CFG		(0X214U)
#define ISP_APBADDR_CFG0	(0X218U)
#define ISP_APBADDR_CFG1	(0X21CU)

/*
 * CSI_CFG
 */
#define CSI_CFG_GEN_APB_RST_SHIFT	(31U)
#define CSI_CFG_GEN_PX_RST_SHIFT	(30U)
#define CSI_CFG_MIPI_SWRST_SHIFT	(29U)
#define CSI_CFG_MIPI_CKMASK_SHIFT	(28U)
#define CSI_CFG_MIPI_CHMUX_3_SHIFT	(27U)
#define CSI_CFG_MIPI_CHMUX_2_SHIFT	(26U)
#define CSI_CFG_MIPI_CHMUX_1_SHIFT	(25U)
#define CSI_CFG_MIPI_CHMUX_0_SHIFT	(24U)
#define CSI_CFG_VSYNC_INV3_SHIFT	(23U)
#define CSI_CFG_VSYNC_INV2_SHIFT	(22U)
#define CSI_CFG_VSYNC_INV1_SHIFT	(21U)
#define CSI_CFG_VSYNC_INV0_SHIFT	(20U)
#define CSI_CFG_CSI_DATA_ALIGN_SHIFT	(16U)
#define CSI_CFG_HSYNC_INV3_SHIFT	(15U)
#define CSI_CFG_HSYNC_INV2_SHIFT	(14U)
#define CSI_CFG_HSYNC_INV1_SHIFT	(13U)
#define CSI_CFG_HSYNC_INV0_SHIFT	(12U)
#define CSI_CFG_LOOPBACK_EN_SHIFT	(9U)
#define CSI_CFG_S_RESETN_SHIFT		(8U)
#define CSI_CFG_M_RESETN_SHIFT		(7U)
#define CSI_CFG_S_FORCERXMODE3_SHIFT	(6U)
#define CSI_CFG_S_FORCERXMODE2_SHIFT	(5U)
#define CSI_CFG_S_FORCERXMODE1_SHIFT	(4U)
#define CSI_CFG_S_FORCERXMODE0_SHIFT	(3U)
#define CSI_CFG_S3_BIASEN_SHIFT		(2U)
#define CSI_CFG_S2_BIASEN_SHIFT		(1U)
#define CSI_CFG_S1_BIASEN_SHIFT		(0U)

#define CSI_CFG_GEN_APB_RST_MASK	((0X1U) << CSI_CFG_GEN_APB_RST_SHIFT)
#define CSI_CFG_GEN_PX_RST_MASK		((0X1U) << CSI_CFG_GEN_PX_RST_SHIFT)
#define CSI_CFG_MIPI_SWRST_MASK		((0X1U) << CSI_CFG_MIPI_SWRST_SHIFT)
#define CSI_CFG_MIPI_CKMASK_MASK	((0X1U) << CSI_CFG_MIPI_CKMASK_SHIFT)
#define CSI_CFG_MIPI_CHMUX_3_MASK	((0X1U) << CSI_CFG_MIPI_CHMUX_3_SHIFT)
#define CSI_CFG_MIPI_CHMUX_2_MASK	((0X1U) << CSI_CFG_MIPI_CHMUX_2_SHIFT)
#define CSI_CFG_MIPI_CHMUX_1_MASK	((0X1U) << CSI_CFG_MIPI_CHMUX_1_SHIFT)
#define CSI_CFG_MIPI_CHMUX_0_MASK	((0X1U) << CSI_CFG_MIPI_CHMUX_0_SHIFT)
#define CSI_CFG_VSYNC_INV3_MASK		((0X1U) << CSI_CFG_VSYNC_INV3_SHIFT)
#define CSI_CFG_VSYNC_INV2_MASK		((0X1U) << CSI_CFG_VSYNC_INV2_SHIFT)
#define CSI_CFG_VSYNC_INV1_MASK		((0X1U) << CSI_CFG_VSYNC_INV1_SHIFT)
#define CSI_CFG_VSYNC_INV0_MASK		((0X1U) << CSI_CFG_VSYNC_INV0_SHIFT)
#define CSI_CFG_CSI_DATA_ALIGN_MASK	((0X3U) << CSI_CFG_CSI_DATA_ALIGN_SHIFT)
#define CSI_CFG_HSYNC_INV3_MASK		((0X1U) << CSI_CFG_HSYNC_INV3_SHIFT)
#define CSI_CFG_HSYNC_INV2_MASK		((0X1U) << CSI_CFG_HSYNC_INV2_SHIFT)
#define CSI_CFG_HSYNC_INV1_MASK		((0X1U) << CSI_CFG_HSYNC_INV1_SHIFT)
#define CSI_CFG_HSYNC_INV0_MASK		((0X1U) << CSI_CFG_HSYNC_INV0_SHIFT)
#define CSI_CFG_LOOPBACK_EN_MASK	((0X1U) << CSI_CFG_LOOPBACK_EN_SHIFT)
#define CSI_CFG_S_RESETN_MASK		((0X1U) << CSI_CFG_S_RESETN_SHIFT)
#define CSI_CFG_M_RESETN_MASK		((0X1U) << CSI_CFG_M_RESETN_SHIFT)
#define CSI_CFG_S_FORCERXMODE3_MASK	((0X1U) << CSI_CFG_S_FORCERXMODE3_SHIFT)
#define CSI_CFG_S_FORCERXMODE2_MASK	((0X1U) << CSI_CFG_S_FORCERXMODE2_SHIFT)
#define CSI_CFG_S_FORCERXMODE1_MASK	((0X1U) << CSI_CFG_S_FORCERXMODE1_SHIFT)
#define CSI_CFG_S_FORCERXMODE0_MASK	((0X1U) << CSI_CFG_S_FORCERXMODE0_SHIFT)
#define CSI_CFG_S3_BIASEN_MASK		((0X1U) << CSI_CFG_S3_BIASEN_SHIFT)
#define CSI_CFG_S2_BIASEN_MASK		((0X1U) << CSI_CFG_S2_BIASEN_SHIFT)
#define CSI_CFG_S1_BIASEN_MASK		((0X1U) << CSI_CFG_S1_BIASEN_SHIFT)

#define CSI_CFG_MIPI_CHMUX_MAX		(8U)

#define CSI_CFG_ISP_BYPASS_MAX		(4U)

#define CSI_DATA_ALIGN_RGB8_YUV8	(0X0U)
#define CSI_DATA_ALIGN_RGB666		(0X1U)
#define CSI_DATA_ALIGN_RGB565		(0X2U)
#define CSI_DATA_ALIGN_YUV10		(0X3U)

/*
 * CSI0 DPHY STATUS0~3
 */
#define CSI0_DPHY_STATUS_S_ATB_OUT_SHIFT	(0U)

#define CSI0_DPHY_STATUS_S_ATB_OUT_MASK		\
		((0xFFFFFFFFU) << CSI0_DPHY_STATUS_S_ATB_OUT_SHIFT)

/*
 * CSI0 DPHY STATUS4
 */
#define CSI0_DPHY_STATUS_S_ERR3_ESC_SHIFT	(8U)
#define CSI0_DPHY_STATUS_S_ERR2_ESC_SHIFT	(7U)
#define CSI0_DPHY_STATUS_S_ERR1_ESC_SHIFT	(6U)
#define CSI0_DPHY_STATUS_S_ERR0_ESC_SHIFT	(5U)
#define CSI0_DPHY_STATUS_S_ERR3CONTROL_SHIFT	(3U)
#define CSI0_DPHY_STATUS_S_ERR2CONTROL_SHIFT	(2U)
#define CSI0_DPHY_STATUS_S_ERR1CONTROL_SHIFT	(1U)
#define CSI0_DPHY_STATUS_S_ERR0CONTROL_SHIFT	(0U)

#define CSI0_DPHY_STATUS_S_ERR3_ESC_MASK	\
		((0X1U) << CSI0_DPHY_STATUS_S_ERR3_ESC_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR2_ESC_MASK	\
		((0X1U) << CSI0_DPHY_STATUS_S_ERR2_ESC_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR1_ESC_MASK	\
		((0X1U) << CSI0_DPHY_STATUS_S_ERR1_ESC_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR0_ESC_MASK	\
		((0X1U) << CSI0_DPHY_STATUS_S_ERR0_ESC_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR3CONTROL_MASK	\
		((0X1U) << CSI0_DPHY_STATUS_S_ERR3CONTROL_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR2CONTROL_MASK	\
		((0X1U) << CSI0_DPHY_STATUS_S_ERR2CONTROL_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR1CONTROL_MASK	\
		((0X1U) << CSI0_DPHY_STATUS_S_ERR1CONTROL_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR0CONTROL_MASK	\
		((0X1U) << CSI0_DPHY_STATUS_S_ERR0CONTROL_SHIFT)

/*
 * ISP_CLK_MASK
 */
#define ISP_CLK_MASK_PX2X_M3_SHIFT	(11U)
#define ISP_CLK_MASK_PX2X_M2_SHIFT	(10U)
#define ISP_CLK_MASK_PX2X_M1_SHIFT	(9U)
#define ISP_CLK_MASK_PX2X_M0_SHIFT	(8U)
#define ISP_CLK_MASK_PX1X_M3_SHIFT	(7U)
#define ISP_CLK_MASK_PX1X_M2_SHIFT	(6U)
#define ISP_CLK_MASK_PX1X_M1_SHIFT	(5U)
#define ISP_CLK_MASK_PX1X_M0_SHIFT	(4U)
#define ISP_CLK_MASK_BCLK_M_SHIFT	(0U)

#define ISP_CLK_MASK_PX2X_M3_MASK	((0X1U) << ISP_CLK_MASK_PX2X_M3_SHIFT)
#define ISP_CLK_MASK_PX2X_M2_MASK	((0X1U) << ISP_CLK_MASK_PX2X_M2_SHIFT)
#define ISP_CLK_MASK_PX2X_M1_MASK	((0X1U) << ISP_CLK_MASK_PX2X_M1_SHIFT)
#define ISP_CLK_MASK_PX2X_M0_MASK	((0X1U) << ISP_CLK_MASK_PX2X_M0_SHIFT)
#define ISP_CLK_MASK_PX1X_M3_MASK	((0X1U) << ISP_CLK_MASK_PX1X_M3_SHIFT)
#define ISP_CLK_MASK_PX1X_M2_MASK	((0X1U) << ISP_CLK_MASK_PX1X_M2_SHIFT)
#define ISP_CLK_MASK_PX1X_M1_MASK	((0X1U) << ISP_CLK_MASK_PX1X_M1_SHIFT)
#define ISP_CLK_MASK_PX1X_M0_MASK	((0X1U) << ISP_CLK_MASK_PX1X_M0_SHIFT)
#define ISP_CLK_MASK_BCLK_M_MASK	((0X1U) << ISP_CLK_MASK_BCLK_M_SHIFT)

/*
 * ISP_SWRST
 */
#define ISP_SWRST_PX2X_SWRST_SHIFT	(20U)
#define ISP_SWRST_PX1X_SWRST_SHIFT	(16U)
#define ISP_SWRST_DDIIF_SWRST_SHIFT	(12U)
#define ISP_SWRST_X2X_SWRST_SHIFT	(8U)
#define ISP_SWRST_AXI_SWRST_SHIFT	(4U)
#define ISP_SWRST_APB_SWRST_SHIFT	(0U)

#define ISP_SWRST_PX2X_SWRST_MASK	((0X1U) << ISP_SWRST_PX2X_SWRST_SHIFT)
#define ISP_SWRST_PX1X_SWRST_MASK	((0X1U) << ISP_SWRST_PX1X_SWRST_SHIFT)
#define ISP_SWRST_DDIIF_SWRST_MASK	((0X1U) << ISP_SWRST_DDIIF_SWRST_SHIFT)
#define ISP_SWRST_X2X_SWRST_MASK	((0X1U) << ISP_SWRST_X2X_SWRST_SHIFT)
#define ISP_SWRST_AXI_SWRST_MASK	((0X1U) << ISP_SWRST_AXI_SWRST_SHIFT)
#define ISP_SWRST_APB_SWRST_MASK	((0X1U) << ISP_SWRST_APB_SWRST_SHIFT)

/*
 * ISP_PX1X_DIV
 */
#define ISP_PX1X_DIV_PX1X_DIV3_SHIFT	(3U)
#define ISP_PX1X_DIV_PX1X_DIV2_SHIFT	(2U)
#define ISP_PX1X_DIV_PX1X_DIV1_SHIFT	(1U)
#define ISP_PX1X_DIV_PX1X_DIV0_SHIFT	(0U)

#define ISP_PX1X_DIV_PX1X_DIV3_MASK	((0X1U) << ISP_PX1X_DIV_PX1X_DIV3_SHIFT)
#define ISP_PX1X_DIV_PX1X_DIV2_MASK	((0X1U) << ISP_PX1X_DIV_PX1X_DIV2_SHIFT)
#define ISP_PX1X_DIV_PX1X_DIV1_MASK	((0X1U) << ISP_PX1X_DIV_PX1X_DIV1_SHIFT)
#define ISP_PX1X_DIV_PX1X_DIV0_MASK	((0X1U) << ISP_PX1X_DIV_PX1X_DIV0_SHIFT)

/*
 * ISP_BYPASS
 */
#define ISP_BYPASS_RVC_SEL_SHIFT	(4U)
#define ISP_BYPASS_ISP3_BYP_SHIFT	(3U)
#define ISP_BYPASS_ISP2_BYP_SHIFT	(2U)
#define ISP_BYPASS_ISP1_BYP_SHIFT	(1U)
#define ISP_BYPASS_ISP0_BYP_SHIFT	(0U)

#define ISP_BYPASS_RVC_SEL_MASK		((0X1U) << ISP_BYPASS_RVC_SEL_SHIFT)
#define ISP_BYPASS_ISP3_BYP_MASK	((0X1U) << ISP_BYPASS_ISP3_BYP_SHIFT)
#define ISP_BYPASS_ISP2_BYP_MASK	((0X1U) << ISP_BYPASS_ISP2_BYP_SHIFT)
#define ISP_BYPASS_ISP1_BYP_MASK	((0X1U) << ISP_BYPASS_ISP1_BYP_SHIFT)
#define ISP_BYPASS_ISP0_BYP_MASK	((0X1U) << ISP_BYPASS_ISP0_BYP_SHIFT)

/*
 * ISP_X2X_CFG
 */
#define ISP_X2X_CFG_PWRDN_BYPASS_SHIFT	(10U)
#define ISP_X2X_CFG_PWRDNACKN_SHIFT	(9U)
#define ISP_X2X_CFG_PWRDNREQN_SHIFT	(4U)
#define ISP_X2X_CFG_ISP_SLEEP_SHIFT	(0U)

#define ISP_X2X_CFG_PWRDN_BYPASS_MASK	\
		((0x1U) << ISP_X2X_CFG_PWRDN_BYPASS_SHIFT)
#define ISP_X2X_CFG_PWRDNACKN_MASK	((0X1U) << ISP_X2X_CFG_PWRDNACKN_SHIFT)
#define ISP_X2X_CFG_PWRDNREQN_MASK	((0x1U) << ISP_X2X_CFG_PWRDNREQN_SHIFT)
#define ISP_X2X_CFG_ISP_SLEEP_MASK	((0x1U) << ISP_X2X_CFG_ISP_SLEEP_SHIFT)

/*
 * ISP_FMT_CFG
 */
#define ISP_FMT_CFG_ISP3_FMT_SHIFT	(12U)
#define ISP_FMT_CFG_ISP2_FMT_SHIFT	(8U)
#define ISP_FMT_CFG_ISP1_FMT_SHIFT	(4U)
#define ISP_FMT_CFG_ISP0_FMT_SHIFT	(0U)

#define ISP_FMT_CFG_ISP3_FMT_MASK	((0X7U) << ISP_FMT_CFG_ISP3_FMT_SHIFT)
#define ISP_FMT_CFG_ISP2_FMT_MASK	((0X7U) << ISP_FMT_CFG_ISP2_FMT_SHIFT)
#define ISP_FMT_CFG_ISP1_FMT_MASK	((0X7U) << ISP_FMT_CFG_ISP1_FMT_SHIFT)
#define ISP_FMT_CFG_ISP0_FMT_MASK	((0X7U) << ISP_FMT_CFG_ISP0_FMT_SHIFT)

#define ISP_FMT_RAW_RGB_8_TO_10_USING_UPPER_2BIT	(0U)
#define ISP_FMT_RAW_RGB_8_TO_10_USING_ZERO		(1U)
#define ISP_FMT_RAW_RGB_10_OR_MORE			(2U)

#endif
